package itson.org.ghosttracks.presentacion.administrador;

import itson.org.ghosttracks.controladores.ControladorGestionArticulos;
import itson.org.ghosttracks.dtos.ProductoDTO;
import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;

/**
 *
 * @author emyla
 */
public class PantallaGestionArticulos extends javax.swing.JPanel {

    private final ControladorGestionArticulos control;
    
    public PantallaGestionArticulos(ControladorGestionArticulos control) {
        this.control = control;
        
        initComponents();
        control.llenarTablaInventario(this); 
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(22);
        configurarEventosFiltros();
    }
    
    public void cargarCatalogo(List<ProductoDTO> productos) {
        if (this.pnlCatalogo.getParent() != null) {
            this.pnlCatalogo.getParent().remove(this.pnlCatalogo);
        }

        this.pnlCatalogo.cargarCatalogo(productos, this.control);

        javax.swing.JPanel contenedorElastico = new javax.swing.JPanel(new java.awt.BorderLayout());
        contenedorElastico.setBackground(new java.awt.Color(237, 229, 222));

        contenedorElastico.add(this.pnlCatalogo, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(contenedorElastico);

        jScrollPane1.revalidate();
        jScrollPane1.repaint();
    }
    
    private void configurarEventosFiltros() {
        txtBuscador.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent evt) {
                dispararFiltro();
            }
        });
        
        cmbTipoArticulo.addItemListener(evt -> {
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                dispararFiltro();
            }
        });
        
        comboBoxRedondeado1.addItemListener(evt -> {
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                dispararFiltro();
            }
        });
    }
    
    private void dispararFiltro() {
        String texto = txtBuscador.getText();
        String tipo = cmbTipoArticulo.getSelectedItem() != null ? cmbTipoArticulo.getSelectedItem().toString() : "Seleccionar tipo";
        String estado = comboBoxRedondeado1.getSelectedItem() != null ? comboBoxRedondeado1.getSelectedItem().toString() : "Seleccionar estado";
        
        control.filtrarInventarioDinamico(this, texto, tipo, estado);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlCatalogo = new itson.org.ghosttracks.utilerias.pnlCatalogo();
        lblTipo = new javax.swing.JLabel();
        cmbTipoArticulo = new itson.org.ghosttracks.utilerias.ComboBoxRedondeado();
        lblEstado = new javax.swing.JLabel();
        comboBoxRedondeado1 = new itson.org.ghosttracks.utilerias.ComboBoxRedondeado();
        txtBuscador = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        botonRedondeado1 = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        botonRedondeado2 = new itson.org.ghosttracks.utilerias.BotonRedondeado();

        setPreferredSize(new java.awt.Dimension(1100, 675));

        jPanel1.setBackground(new java.awt.Color(237, 229, 222));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 675));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(pnlCatalogo);

        lblTipo.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipo.setText("Tipo de artículo:");

        cmbTipoArticulo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar tipo", "CD", "Vinilo", "Cassette" }));
        cmbTipoArticulo.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N

        lblEstado.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEstado.setText("Estado:");

        comboBoxRedondeado1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar estado", "Disponible", "Agotado" }));
        comboBoxRedondeado1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N

        txtBuscador.setToolTipText("");
        txtBuscador.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtBuscador.addActionListener(this::txtBuscadorActionPerformed);

        botonRedondeado1.setBackground(new java.awt.Color(191, 64, 43));
        botonRedondeado1.setForeground(new java.awt.Color(255, 255, 255));
        botonRedondeado1.setText("Nuevo artículo");
        botonRedondeado1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        botonRedondeado1.addActionListener(this::botonRedondeado1ActionPerformed);

        botonRedondeado2.setBackground(new java.awt.Color(191, 64, 43));
        botonRedondeado2.setForeground(new java.awt.Color(255, 255, 255));
        botonRedondeado2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        botonRedondeado2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRedondeado2.setLabel("Generar reporte");
        botonRedondeado2.setPreferredSize(new java.awt.Dimension(167, 31));
        botonRedondeado2.addActionListener(this::botonRedondeado2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonRedondeado2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblEstado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTipo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbTipoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipo)
                            .addComponent(cmbTipoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstado)
                            .addComponent(comboBoxRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRedondeado2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void botonRedondeado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRedondeado1ActionPerformed
        control.abrirRegistroProducto();
    }//GEN-LAST:event_botonRedondeado1ActionPerformed

    private void botonRedondeado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRedondeado2ActionPerformed
        control.abrirReporteInventario();
    }//GEN-LAST:event_botonRedondeado2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.org.ghosttracks.utilerias.BotonRedondeado botonRedondeado1;
    private itson.org.ghosttracks.utilerias.BotonRedondeado botonRedondeado2;
    private itson.org.ghosttracks.utilerias.ComboBoxRedondeado cmbTipoArticulo;
    private itson.org.ghosttracks.utilerias.ComboBoxRedondeado comboBoxRedondeado1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblTipo;
    private itson.org.ghosttracks.utilerias.pnlCatalogo pnlCatalogo;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtBuscador;
    // End of variables declaration//GEN-END:variables
}
