/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.org.ghosttracks.presentacion.administrador;

import itson.org.ghosttracks.controladores.ControladorGestionArticulos;
import itson.org.ghosttracks.dtos.GeneroDTO;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author emyla
 */
public class PantallaNuevoProducto extends javax.swing.JPanel {

    private ControladorGestionArticulos ctrl;
    private File archivoImagenSeleccionado = null;
    /**
     * Creates new form pnlNuevoProducto
     */
    public PantallaNuevoProducto(ControladorGestionArticulos ctrl) {
        initComponents();
        this.ctrl = ctrl;
        cargarGenerosEnCombo();
    }
    
    private void cargarGenerosEnCombo() {
        // Limpiamos el modelo estático que le puso NetBeans por defecto
        cmbGenero.removeAllItems(); 

        // Añadimos una opción por defecto 
        cmbGenero.addItem("Seleccionar género"); 

        // Traemos los géneros reales desde el controlador y los metemos al combo
        List<GeneroDTO> generos = ctrl.obtenerListaGeneros();
        for (GeneroDTO g : generos) {
            cmbGenero.addItem(g); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        cmbTipoArticulo = new itson.org.ghosttracks.utilerias.ComboBoxRedondeado();
        lblEstado = new javax.swing.JLabel();
        cmbGenero = new itson.org.ghosttracks.utilerias.ComboBoxRedondeado();
        txtTitulo = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        botonRedondeado1 = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        botonRedondeado2 = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        panelRedondeado1 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEstado1 = new javax.swing.JLabel();
        txtArtista = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        lblEstado2 = new javax.swing.JLabel();
        lblEstado3 = new javax.swing.JLabel();
        lblEstado4 = new javax.swing.JLabel();
        txtPrecio = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        lblEstado5 = new javax.swing.JLabel();
        txtStock = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();

        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 675));

        jPanel2.setBackground(new java.awt.Color(237, 229, 222));
        jPanel2.setPreferredSize(new java.awt.Dimension(1100, 675));

        label.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label.setText("NUEVO ARTÍCULO");

        cmbTipoArticulo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar tipo", "CD", "Vinilo", "Cassette" }));
        cmbTipoArticulo.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N

        lblEstado.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEstado.setText("Artista:");

        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar género", "Rock", "Alternativo", "Rap", "Rock en español", "Hip hop" }));
        cmbGenero.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N

        txtTitulo.setToolTipText("");
        txtTitulo.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtTitulo.addActionListener(this::txtTituloActionPerformed);

        botonRedondeado1.setBackground(new java.awt.Color(191, 64, 43));
        botonRedondeado1.setForeground(new java.awt.Color(255, 255, 255));
        botonRedondeado1.setText("Guardar");
        botonRedondeado1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        botonRedondeado1.addActionListener(this::botonRedondeado1ActionPerformed);

        botonRedondeado2.setBackground(new java.awt.Color(145, 145, 145));
        botonRedondeado2.setForeground(new java.awt.Color(255, 255, 255));
        botonRedondeado2.setText("Cancelar");
        botonRedondeado2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        botonRedondeado2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRedondeado2.setPreferredSize(new java.awt.Dimension(167, 31));
        botonRedondeado2.addActionListener(this::botonRedondeado2ActionPerformed);

        panelRedondeado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRedondeado1MouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoSubir.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SUBIR ARCHIVO");

        javax.swing.GroupLayout panelRedondeado1Layout = new javax.swing.GroupLayout(panelRedondeado1);
        panelRedondeado1.setLayout(panelRedondeado1Layout);
        panelRedondeado1Layout.setHorizontalGroup(
            panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelRedondeado1Layout.setVerticalGroup(
            panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        lblEstado1.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblEstado1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEstado1.setText("Titulo:");

        txtArtista.setToolTipText("");
        txtArtista.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtArtista.addActionListener(this::txtArtistaActionPerformed);

        lblEstado2.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblEstado2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEstado2.setText("Tipo de producto:");

        lblEstado3.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblEstado3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEstado3.setText("Género:");

        lblEstado4.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblEstado4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEstado4.setText("Precio:");

        txtPrecio.setToolTipText("");
        txtPrecio.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtPrecio.addActionListener(this::txtPrecioActionPerformed);

        lblEstado5.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblEstado5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEstado5.setText("Stock inicial:");

        txtStock.setToolTipText("");
        txtStock.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtStock.addActionListener(this::txtStockActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblEstado5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label)
                            .addComponent(lblEstado2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonRedondeado2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(botonRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(panelRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lblEstado3)
                                            .addGap(298, 298, 298)
                                            .addComponent(lblEstado4))
                                        .addComponent(lblEstado1)
                                        .addComponent(lblEstado)
                                        .addComponent(txtArtista, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                                        .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(cmbTipoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(20, 77, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(label)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblEstado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(lblEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstado4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEstado2)
                        .addComponent(lblEstado3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(lblEstado5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonRedondeado2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(botonRedondeado1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void botonRedondeado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRedondeado1ActionPerformed
        try{
            String titulo = txtTitulo.getText().trim();
            String artista = txtArtista.getText().trim();

            if (titulo.isEmpty() || artista.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                        "El título y el artista son obligatorios y no pueden contener solo espacios en blanco.", 
                        "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (cmbTipoArticulo.getSelectedIndex() <= 0) { 
                JOptionPane.showMessageDialog(this, 
                        "Por favor, selecciona un tipo de artículo válido (CD, Vinilo o Cassette).", 
                        "Tipo no seleccionado", JOptionPane.WARNING_MESSAGE);
                return;
            }
            String tipo = cmbTipoArticulo.getSelectedItem().toString();

            Object itemSeleccionado = cmbGenero.getSelectedItem();
            if (itemSeleccionado == null || itemSeleccionado instanceof String || cmbGenero.getSelectedIndex() <= 0) {
                JOptionPane.showMessageDialog(this, 
                        "Por favor, selecciona un género válido de la lista.", 
                        "Género no seleccionado", JOptionPane.WARNING_MESSAGE);
                return; 
            }
            GeneroDTO generoSelected = (GeneroDTO) itemSeleccionado;
            String idGenero = generoSelected.getId(); 

            String precioRaw = txtPrecio.getText().trim();
            if (precioRaw.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo de precio no puede estar vacío.", "Precio Vacío", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Double precio = Double.parseDouble(precioRaw);
            if (precio <= 0) {
                JOptionPane.showMessageDialog(this, "El precio debe ser un número mayor a cero.", "Precio Inválido", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String stockRaw = txtStock.getText().trim();
            if (stockRaw.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo de stock no puede estar vacío.", "Stock Vacío", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Integer stock = Integer.parseInt(stockRaw);
            if (stock < 0) {
                JOptionPane.showMessageDialog(this, "El stock inicial no puede ser un número negativo.", "Stock Inválido", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (this.archivoImagenSeleccionado == null) {
                JOptionPane.showMessageDialog(this, 
                        "Debes seleccionar una imagen para el artículo haciendo clic en el panel 'SUBIR ARCHIVO'.", 
                        "Imagen Requerida", JOptionPane.WARNING_MESSAGE);
                return;
            }

            ctrl.procesarRegistroProducto(titulo, artista, tipo, idGenero, precio, stock, this.archivoImagenSeleccionado);

            JOptionPane.showMessageDialog(this, "Artículo registrado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, 
                    "Error de formato: Asegúrate de ingresar un número decimal válido para el precio (ej. 299.90) y un número entero para el stock.", 
                    "Error de Formato Numérico", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, 
                    "Ocurrió un error inesperado al guardar el producto: " + ex.getMessage(), 
                    "Error General", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_botonRedondeado1ActionPerformed

    private void botonRedondeado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRedondeado2ActionPerformed
    ctrl.regresarAlCatalogo();
    }//GEN-LAST:event_botonRedondeado2ActionPerformed

    private void txtArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArtistaActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void panelRedondeado1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRedondeado1MouseClicked
        JFileChooser selector = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imágenes", "png", "jpg", "jpeg");
        selector.setFileFilter(filtro);

        if (selector.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            this.archivoImagenSeleccionado = selector.getSelectedFile();
            System.out.println("Archivo seleccionado listo: " + archivoImagenSeleccionado.getName());
        }
    }//GEN-LAST:event_panelRedondeado1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.org.ghosttracks.utilerias.BotonRedondeado botonRedondeado1;
    private itson.org.ghosttracks.utilerias.BotonRedondeado botonRedondeado2;
    private itson.org.ghosttracks.utilerias.ComboBoxRedondeado cmbGenero;
    private itson.org.ghosttracks.utilerias.ComboBoxRedondeado cmbTipoArticulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblEstado2;
    private javax.swing.JLabel lblEstado3;
    private javax.swing.JLabel lblEstado4;
    private javax.swing.JLabel lblEstado5;
    private itson.org.ghosttracks.utilerias.PanelRedondeado panelRedondeado1;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtArtista;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtPrecio;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtStock;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtTitulo;
    // End of variables declaration//GEN-END:variables
}
